/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.KhachHang_DAO;
import entity.CT_HoaDon;
import entity.HoaDon;
import entity.NhanVien;
import java.awt.Color;
import java.awt.Font;
import java.text.DecimalFormat;

import java.time.LocalDate;
import java.util.ArrayList;

/**
 *
 * @author Thien Long
 */
public class Frame_HoaDon extends javax.swing.JFrame {
    
    private HoaDon hd;
    private ArrayList<CT_HoaDon> gioHang;
    private NhanVien nv;
    private KhachHang_DAO kh_dao = new KhachHang_DAO();
    double tongTien = 0;
    double tienNhan = 0;
    double tienThua = 0;
    int diemTL = 0;
    /**
     * Creates new form Frame_DonHang
     */
    public Frame_HoaDon(HoaDon hoadon, ArrayList<CT_HoaDon> gioHang, NhanVien nv,  double tongTien, double tienNhan, double tienThua, int diemTL) {
        initComponents();
        this.hd = hoadon;
        this.gioHang = gioHang;
        this.nv = nv;
        this.tongTien = tongTien;
        this.tienNhan = tienNhan;
        this.tienThua = tienThua;
        this.diemTL = diemTL;
        hoaDontxt.setEditable(false);
        hoaDontxt.setEnabled(false);
        hoaDontxt.setDisabledTextColor(Color.BLACK);
        hoaDontxt.setFont(new Font("Courier", Font.PLAIN, this.getFont().getSize()));
        render();
    }
    
    public void render() {
        DecimalFormat df = new DecimalFormat("#, ### VND");
        String line = "\n ------------------------------------------------------------------------------------------------------------------------------------------------------------\n";
        String result = String.format("%50s", "Hóa đơn bán hàng");
        result += line;
        result += " Mã hóa đơn: " + hd.getMaHD();
        result += "\n Ngày lập: " + LocalDate.now().toString();

        if (hd.getKH() != null) {
            result += "\n Khách hàng: " + hd.getKH().getTenKH();
            result += "\n Số điện thoại: " + hd.getKH().getSdt();
        } else {
            result += "\n Khách hàng: Không";
        }
        if (nv != null) {
            result += "\n Nhân viên: " + nv.getTen();
        } else {
            result += "\n Nhân viên: Không";
        }
        result += line;
        result += String.format(" %5s %10s %40s %35s %25s %25s", "STT", "Mã SP", "Tên sản phẩm", "Đơn giá", "Số lượng", "Thành tiền");
        int i = 1;
        for (CT_HoaDon ct : gioHang) {
            result += "\n" + String.format(" %5d %10s %40s %35s %25d %25s", i, ct.getSanPham().getMaSP(), ct.getSanPham().getTenSP(), df.format(ct.getSanPham().getGiaNhap()*(1- ct.getChietKhau())), ct.getSoLuong(), df.format((ct.getSanPham().getGiaNhap() * (1 - ct.getChietKhau())) * ct.getSoLuong()));
            i++;
        }
        //thêm thuế
        result += "\n   Thuế: 10%";
        result += line;
        result += "   Giảm giá: " + df.format(diemTL);
        result += "\n   Tổng tiền: " + df.format(tongTien);
        result += "\n   Tiền khách đưa: " + df.format(tienNhan);
        result += "\n   Tiền thừa: " + df.format(tienThua);
        hoaDontxt.setText(result);
        congDiemChoKh(tongTien);
        this.setSize(650, 500);
        this.setLocationRelativeTo(null);
    }
    
    public void congDiemChoKh(double tongTien) {
        int diem = (int) (tongTien * 0.01);
        if (hd.getKH() != null) {
            int diemCu = hd.getKH().getDiemTL();
            hd.getKH().setDiemTL(diemCu + diem);
            kh_dao.update(hd.getKH());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_xacNhan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hoaDontxt = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        confirmBtn = new javax.swing.JButton();

        btn_xacNhan.setBackground(new java.awt.Color(65, 165, 238));
        btn_xacNhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btn_xacNhan.setText("Xác nhận");
        btn_xacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_xacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xacNhanActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hoaDontxt.setColumns(20);
        hoaDontxt.setRows(5);
        jScrollPane1.setViewportView(hoaDontxt);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        confirmBtn.setBackground(new java.awt.Color(0, 153, 153));
        confirmBtn.setText("Xác nhận");
        confirmBtn.setPreferredSize(new java.awt.Dimension(100, 20));
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });
        jPanel1.add(confirmBtn);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void btn_xacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xacNhanActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_xacNhanActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_xacNhan;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JTextArea hoaDontxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
