/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import connectdb.ConnectDB;
import entity.NhanVien;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Thien Long
 */
public final class Home extends javax.swing.JFrame {
    
    NhanVien nv = null;
    CardLayout card;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        card = (CardLayout)pMain.getLayout();
        logout();
        disableAllFunction();
    }

    public void logout() {
        this.nv = null;

        this.lbl_name.setText("");
        this.jButton1.setVisible(false);
        this.btnLogin.setVisible(true);
        pMain.add(pHome, "home");
        this.card.show(pMain, "home");
        buttonActive(jLabel3);
        disableAllFunction();
        
        ConnectDB.disconnect();
    }
    
    public void login(NhanVien nv) {
        this.nv = nv;
        this.lbl_name.setVisible(true);
        this.lbl_name.setText(nv.getHo() + " " + nv.getTen() + "(" + nv.getMaNV() + ")");
        this.jButton1.setVisible(true);
        this.btnLogin.setVisible(false);
        activeAllFunction();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lbl_name = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnCart = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnInvoice = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pMain = new javax.swing.JPanel();
        pHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pCart = new javax.swing.JPanel();
        pInvoice = new javax.swing.JPanel();
        pProduct = new javax.swing.JPanel();
        pCustomer = new javax.swing.JPanel();
        pEmployee = new javax.swing.JPanel();
        pThongKe = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setPreferredSize(new java.awt.Dimension(909, 50));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5);
        flowLayout1.setAlignOnBaseline(true);
        jPanel5.setLayout(flowLayout1);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Đăng Xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        btnLogin.setBackground(new java.awt.Color(0, 102, 102));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Đăng nhập");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel5.add(btnLogin);
        jPanel5.add(lbl_name);
        jPanel5.add(filler1);

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 385));
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo__2_-removebg-preview.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setPreferredSize(new java.awt.Dimension(201, 500));

        btnCart.setBackground(new java.awt.Color(0, 153, 153));
        btnCart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCart.setForeground(new java.awt.Color(255, 255, 255));
        btnCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/banhangg (1).png"))); // NOI18N
        btnCart.setText("Bán Hàng");
        btnCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCartMouseClicked(evt);
            }
        });
        btnCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartActionPerformed(evt);
            }
        });

        btnProduct.setBackground(new java.awt.Color(0, 153, 153));
        btnProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sanpham-removebg-preview (2).png"))); // NOI18N
        btnProduct.setText("Sản  Phẩm");
        btnProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductMouseClicked(evt);
            }
        });

        btnCustomer.setBackground(new java.awt.Color(0, 153, 153));
        btnCustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/khachhang-removebg-preview (1).png"))); // NOI18N
        btnCustomer.setText("Khách Hàng");
        btnCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerMouseClicked(evt);
            }
        });

        btnEmployee.setBackground(new java.awt.Color(0, 153, 153));
        btnEmployee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nhanvienn-removebg-preview (1).png"))); // NOI18N
        btnEmployee.setText("Nhân Viên");
        btnEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmployeeMouseClicked(evt);
            }
        });

        btnThongKe.setBackground(new java.awt.Color(0, 153, 153));
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(255, 255, 255));
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thongkee-removebg-preview (1).png"))); // NOI18N
        btnThongKe.setText("Thống Kê");
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThongKeMouseClicked(evt);
            }
        });

        btnInvoice.setBackground(new java.awt.Color(0, 153, 153));
        btnInvoice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInvoice.setForeground(new java.awt.Color(255, 255, 255));
        btnInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hoadon (1).png"))); // NOI18N
        btnInvoice.setText("Hóa Đơn");
        btnInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInvoiceMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInvoice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCart, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnProduct)
                .addGap(30, 30, 30)
                .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.LINE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(1448, 50));

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cửa Hàng Tiện Lợi G2G");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1019, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        pMain.setLayout(new java.awt.CardLayout());

        pHome.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        pHome.add(jLabel1, java.awt.BorderLayout.CENTER);

        pMain.add(pHome, "card3");

        pCart.setPreferredSize(new java.awt.Dimension(1756, 600));
        pCart.setLayout(new java.awt.BorderLayout());
        pMain.add(pCart, "card4");

        javax.swing.GroupLayout pInvoiceLayout = new javax.swing.GroupLayout(pInvoice);
        pInvoice.setLayout(pInvoiceLayout);
        pInvoiceLayout.setHorizontalGroup(
            pInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1756, Short.MAX_VALUE)
        );
        pInvoiceLayout.setVerticalGroup(
            pInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );

        pMain.add(pInvoice, "card8");

        javax.swing.GroupLayout pProductLayout = new javax.swing.GroupLayout(pProduct);
        pProduct.setLayout(pProductLayout);
        pProductLayout.setHorizontalGroup(
            pProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1756, Short.MAX_VALUE)
        );
        pProductLayout.setVerticalGroup(
            pProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );

        pMain.add(pProduct, "card5");

        javax.swing.GroupLayout pCustomerLayout = new javax.swing.GroupLayout(pCustomer);
        pCustomer.setLayout(pCustomerLayout);
        pCustomerLayout.setHorizontalGroup(
            pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1756, Short.MAX_VALUE)
        );
        pCustomerLayout.setVerticalGroup(
            pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );

        pMain.add(pCustomer, "card7");

        javax.swing.GroupLayout pEmployeeLayout = new javax.swing.GroupLayout(pEmployee);
        pEmployee.setLayout(pEmployeeLayout);
        pEmployeeLayout.setHorizontalGroup(
            pEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1756, Short.MAX_VALUE)
        );
        pEmployeeLayout.setVerticalGroup(
            pEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );

        pMain.add(pEmployee, "card6");

        javax.swing.GroupLayout pThongKeLayout = new javax.swing.GroupLayout(pThongKe);
        pThongKe.setLayout(pThongKeLayout);
        pThongKeLayout.setHorizontalGroup(
            pThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1756, Short.MAX_VALUE)
        );
        pThongKeLayout.setVerticalGroup(
            pThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );

        pMain.add(pThongKe, "card8");

        jPanel2.add(pMain, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        new Login(this).setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        pMain.add(pHome, "home");
        card.show(pMain, "home");
        buttonActive(evt.getComponent());
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCartMouseClicked
        // TODO add your handling code here:
        pCart = new Panel_BanHang(nv);
        pMain.add(pCart, "cart");
        card.show(pMain, "cart");
        buttonActive(evt.getComponent());
    }//GEN-LAST:event_btnCartMouseClicked

    private void btnProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductMouseClicked
        // TODO add your handling code here:
        pProduct = new Panel_QuanLySanPham();
        pMain.add(pProduct, "product");
        card.show(pMain, "product");
        buttonActive(evt.getComponent());
    }//GEN-LAST:event_btnProductMouseClicked

    private void btnCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerMouseClicked
        // TODO add your handling code here:
        pCustomer = new Panel_QuanLyKhachHang();
        pMain.add(pCustomer, "customer");
        card.show(pMain, "customer");
        buttonActive(evt.getComponent());
    }//GEN-LAST:event_btnCustomerMouseClicked

    private void btnEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeeMouseClicked
        // TODO add your handling code here:
        pEmployee = new Panel_NhanVien();
        pMain.add(pEmployee, "employee");
        card.show(pMain, "employee");
        buttonActive(evt.getComponent());
    }//GEN-LAST:event_btnEmployeeMouseClicked

    private void btnThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseClicked
        // TODO add your handling code here:
        pThongKe = new ThongKe();
        pMain.add(pThongKe, "tk");
        card.show(pMain, "tk");
        buttonActive(evt.getComponent());
    }//GEN-LAST:event_btnThongKeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn đăng xuất?", "Đăng xuất", JOptionPane.YES_OPTION) == JOptionPane.YES_OPTION) {
            logout();
            ConnectDB.disconnect();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvoiceMouseClicked
        // TODO add your handling code here:
        pInvoice = new Panel_HoaDon();
        pMain.add(pInvoice, "invoice");
        card.show(pMain, "invoice");
        buttonActive(evt.getComponent());
    }//GEN-LAST:event_btnInvoiceMouseClicked

    private void btnCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
               
            }
        });
    }
    
    public void disableAllFunction() {
        Arrays.stream(new Component[]{btnCart, btnCustomer, btnInvoice, btnEmployee, btnProduct, btnThongKe}).forEach(item -> item.setVisible(false));
    }

    public void activeAllFunction() {
        Arrays.stream(new Component[]{btnCart, btnInvoice, btnCustomer, btnEmployee, btnProduct, btnThongKe}).forEach(item -> item.setVisible(true));
        
    }
    
    private void buttonActive(Component c) {
        Arrays.stream(new Component[]{btnCart, btnInvoice, btnCustomer, btnEmployee, btnProduct, btnThongKe}).forEach(item -> item.setBackground(new Color(0, 153, 153)));
        c.setBackground(Color.DARK_GRAY);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCart;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnInvoice;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnThongKe;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JPanel pCart;
    private javax.swing.JPanel pCustomer;
    private javax.swing.JPanel pEmployee;
    private javax.swing.JPanel pHome;
    private javax.swing.JPanel pInvoice;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel pProduct;
    private javax.swing.JPanel pThongKe;
    // End of variables declaration//GEN-END:variables
}
