/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.CT_HoaDon_DAO;
import dao.HoaDon_DAO;
import dao.SanPham_DAO;
import entity.CT_HoaDon;
import entity.HoaDon;
import entity.KhachHang;
import entity.NhanVien;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguye
 */
public class Panel_HoaDon extends javax.swing.JPanel {

    private DefaultTableModel modelHD;
    private HoaDon_DAO hd_dao;
    private CT_HoaDon_DAO ct_dao;
    private SanPham_DAO sp_dao;
    private ArrayList<HoaDon> dshd;
    private ArrayList<CT_HoaDon> dscthd;
    /**
     * Creates new form Panel_HoaDon
     */
    public Panel_HoaDon() {
        modelHD = new DefaultTableModel(new String[]{"Mã Hóa Đơn", "Mã khách hàng", "Ngày Lập HD", "Mã Nhân Viên"}, 0);
        initComponents();
        hd_dao = new HoaDon_DAO();
        ct_dao = new CT_HoaDon_DAO();
        sp_dao = new SanPham_DAO();
        dshd = hd_dao.getAllHoaDon();
        docDuLieuTuListVaoTable(dshd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTimHD = new javax.swing.JTextField();
        btnTimHD = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        lbl_MaHD = new javax.swing.JLabel();
        lbl_NgayLapHD = new javax.swing.JLabel();
        lbl_MaKH = new javax.swing.JLabel();
        txt_MaKH = new javax.swing.JTextField();
        txtMa = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ngayLapHD = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_hd = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 500));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 70));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mã Hóa Đơn");

        btnTimHD.setBackground(new java.awt.Color(0, 102, 102));
        btnTimHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimHD.setForeground(new java.awt.Color(255, 255, 255));
        btnTimHD.setText("Tìm Kiếm");
        btnTimHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtTimHD, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnTimHD, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTimHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 396));

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/avatar (1).png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Thông Tin Nhân Viên");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(77, 77, 77))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        lbl_MaHD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_MaHD.setForeground(new java.awt.Color(255, 255, 255));
        lbl_MaHD.setText("Mã Hóa Đơn");

        lbl_NgayLapHD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_NgayLapHD.setForeground(new java.awt.Color(255, 255, 255));
        lbl_NgayLapHD.setText("Ngày lập HD");

        lbl_MaKH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_MaKH.setForeground(new java.awt.Color(255, 255, 255));
        lbl_MaKH.setText("Mã Khách Hàng");

        txt_MaKH.setEditable(false);
        txt_MaKH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_MaKH.setForeground(new java.awt.Color(0, 0, 204));
        txt_MaKH.setDisabledTextColor(new java.awt.Color(0, 204, 204));
        txt_MaKH.setEnabled(false);

        txtMa.setEditable(false);
        txtMa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMa.setForeground(new java.awt.Color(0, 0, 204));
        txtMa.setDisabledTextColor(new java.awt.Color(0, 204, 204));
        txtMa.setEnabled(false);

        txtMaNV.setEditable(false);
        txtMaNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMaNV.setForeground(new java.awt.Color(0, 0, 204));
        txtMaNV.setDisabledTextColor(new java.awt.Color(0, 204, 204));
        txtMaNV.setEnabled(false);
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Mã Nhân Viên");

        ngayLapHD.setAutoscrolls(true);
        ngayLapHD.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_MaHD)
                        .addComponent(lbl_NgayLapHD, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(lbl_MaKH, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_MaKH, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(txtMa, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(ngayLapHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lbl_MaHD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MaKH)
                    .addComponent(txt_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(ngayLapHD, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_NgayLapHD)
                        .addGap(29, 29, 29)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel9.setPreferredSize(new java.awt.Dimension(490, 300));
        jPanel9.setLayout(new java.awt.BorderLayout());

        tb_hd.setModel(modelHD);
        tb_hd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_hdMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_hd);

        jPanel9.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        btnDelete.setBackground(new java.awt.Color(0, 102, 102));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(0, 102, 102));
        btnView.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("Xem chi tiết");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(0, 102, 102));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Làm mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel10, java.awt.BorderLayout.SOUTH);

        jPanel5.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimHDActionPerformed
        // TODO add your handling code here:
        String maHD = txtTimHD.getText();
        
        ArrayList<HoaDon> dsHoaDons = new ArrayList<>();
        if (maHD.equals("") || maHD.isEmpty()) {
            xoaHetDuLieuTable();
            docDuLieuTuListVaoTable(hd_dao.getAllHoaDon());
            JOptionPane.showMessageDialog(this, "Nhập mã hóa đơn cần tìm?", "Tìm kiếm hóa đơn", JOptionPane.ERROR_MESSAGE);
            txtTimHD.grabFocus();
        } else {
            xoaHetDuLieuTable();
            for (HoaDon hoaDon : hd_dao.getAllHoaDon()) {
                if (hoaDon.getMaHD().toLowerCase().contains(maHD.toLowerCase())) {
                    dsHoaDons.add(hoaDon);
                }
            }
            if (dsHoaDons.size() > 0) {
                
                docDuLieuTuListVaoTable(dsHoaDons);
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy hóa đơn", "Tìm kiếm hóa đơn", JOptionPane.WARNING_MESSAGE);
                docDuLieuTuListVaoTable(dshd);
            }
        }
    }//GEN-LAST:event_btnTimHDActionPerformed

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int rowSelected = tb_hd.getSelectedRow();
        if (rowSelected >= 0) {
            String maHD = txtMa.getText();
            String maKH = txt_MaKH.getText();
            LocalDate ngayLap = LocalDateTime.ofInstant(ngayLapHD.getDate().toInstant(), ZoneId.systemDefault()).toLocalDate();
            String maNV = txtMaNV.getText();

            HoaDon hd = new HoaDon(maHD, ngayLap, new KhachHang(maKH), new NhanVien(maNV));
            if (JOptionPane.showConfirmDialog(this, "Xác nhận xóa hóa đơn này?", "Xóa hóa đơn", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION) {
                if (ct_dao.xoaCTHoaDonTheoMa(maHD)) {
                    if (hd_dao.delete(hd)) {
                        JOptionPane.showMessageDialog(this, "Xóa thành công", "Xóa hóa đơn", JOptionPane.INFORMATION_MESSAGE);
                        xoaHetDuLieuTable();
                        docDuLieuTuListVaoTable(hd_dao.getAllHoaDon());
                    }
                }

            }
        } else {
            JOptionPane.showMessageDialog(this, "Chọn nhân viên cần xóa",  "Xóa nhân viên", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        xoaHetDuLieuTable();
        docDuLieuTuListVaoTable(hd_dao.getAllHoaDon());
        txtMa.setText(null);
        txt_MaKH.setText(null);
        tb_hd.clearSelection();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int rowSelected = tb_hd.getSelectedRow();
        if (rowSelected > -1) {
            String maHD = modelHD.getValueAt(rowSelected, 0).toString();
            JFrame frame_CTHD = new JFrame();
            frame_CTHD.setTitle("Chi tiết hóa đơn");
            frame_CTHD.setLocationRelativeTo(null);
            frame_CTHD.setLayout(new BorderLayout());
            frame_CTHD.setSize(500, 200);
            DefaultTableModel modelCTHD = new DefaultTableModel(new String[] {"Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Đơn giá", "Thành Tiền"}, 0);
            JTable tbCT = new JTable(modelCTHD);
            dscthd = ct_dao.getALlCTHDTheoMa(maHD);
            double total = 0;
            for (CT_HoaDon ct : dscthd) {
                modelCTHD.addRow(new Object[]{
                    ct.getSanPham().getMaSP(), ct.getSanPham().getTenSP(), ct.getSoLuong(), ct.getSanPham().getGiaNhap()*(1-ct.getChietKhau()), ct.getSanPham().getGiaNhap()*ct.getSoLuong()*(1-ct.getChietKhau())
                });
                total += ct.getSanPham().getGiaNhap()*ct.getSoLuong()*(1-ct.getChietKhau());
            }
            JPanel pnl_tbct = new JPanel();
            pnl_tbct.add(new JScrollPane(tbCT), BorderLayout.CENTER);
            pnl_tbct.setBorder(BorderFactory.createTitledBorder("Chi Tiết Hóa Đơn " + maHD));
            frame_CTHD.add(pnl_tbct, BorderLayout.CENTER);
            JButton btnDong = new JButton("Đóng");
            btnDong.setBackground(Color.red);
            JPanel pnl_btn = new JPanel(new FlowLayout());
            Box b = Box.createVerticalBox();
            pnl_btn.add(b);
            b.add(new JLabel("Tổng hóa đơn (đã bao gồm thuế): " + String.format("%.0f VND", total*1.1)));
            b.add(new JPanel(new BorderLayout()).add(btnDong));
            frame_CTHD.add(pnl_btn, BorderLayout.SOUTH);
            btnDong.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    frame_CTHD.setVisible(false);
                }
            });
            frame_CTHD.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Chọn hóa đơn cần xem thông tin chi tiết",  "Xem thông tin hóa đơn", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void tb_hdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_hdMouseClicked
        // TODO add your handling code here:
        int seletedRow = tb_hd.getSelectedRow();
        txtMa.setText(modelHD.getValueAt(seletedRow, 0).toString());
        txt_MaKH.setText(modelHD.getValueAt(seletedRow, 1).toString());
        try {
            ngayLapHD.setDate(new SimpleDateFormat("dd-MM-yyyy").parse(modelHD.getValueAt(seletedRow, 2).toString()));
            ngayLapHD.invalidate();
        } catch (ParseException ex) {
            Logger.getLogger(Panel_HoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtMaNV.setText(modelHD.getValueAt(seletedRow, 3).toString());
    }//GEN-LAST:event_tb_hdMouseClicked

    public void xoaHetDuLieuTable() {
        DefaultTableModel dtm = (DefaultTableModel)tb_hd.getModel();
        dtm.getDataVector().removeAllElements();
    }
    
    public void docDuLieuTuListVaoTable(ArrayList<HoaDon> dshd) {
        for (HoaDon hd : dshd) {
            modelHD.addRow(new Object[] {
                hd.getMaHD(), hd.getKH().getMaKH(), hd.getNgayLapHD().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")), hd.getNv().getMaNV()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTimHD;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_MaHD;
    private javax.swing.JLabel lbl_MaKH;
    private javax.swing.JLabel lbl_NgayLapHD;
    private com.toedter.calendar.JDateChooser ngayLapHD;
    private javax.swing.JTable tb_hd;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtTimHD;
    private javax.swing.JTextField txt_MaKH;
    // End of variables declaration//GEN-END:variables
}
