/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import connectdb.ConnectDB;
import dao.NhaCungCap_DAO;
import dao.NhomSanPham_DAO;
import dao.SanPham_DAO;
import entity.CT_HoaDon;
import entity.NhaCungCap;
import entity.NhomSanPham;
import entity.SanPham;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Panel_QuanLySanPham extends javax.swing.JPanel {

    private SanPham_DAO sp_dao;
    private NhomSanPham_DAO nsp_dao;
    private ArrayList<SanPham> dssp;
    private ArrayList<CT_HoaDon> dscthd;
    private ArrayList<NhomSanPham> dsnsp; 
    private ArrayList<NhaCungCap> dsncc;
    DefaultTableModel modelSanPham;
    /**
     * Creates new form Panel_QuanLySanPham
     */
    public Panel_QuanLySanPham() {
        try {
            ConnectDB.connect();
        } catch (SQLException ex) {
            Logger.getLogger(Panel_QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
        String[] col = {"Mã sản phẩm", "Tên sản phẩm", "Mô tả", "Đơn vị tính", "Đơn giá", "Số lượng tồn", "Ngày nhập", "Ngày sản xuất", "Ngày hết hạn", "Nhóm sản phẩm", "Nhà cung cấp"};
        modelSanPham = new DefaultTableModel(col, 0);
        
        initComponents();
        
        
        sp_dao = new SanPham_DAO();
        nsp_dao = new NhomSanPham_DAO();
        dsnsp = nsp_dao.getAllNSP();
        dsncc = new NhaCungCap_DAO().getallNCC();
        dsnsp.forEach(x -> cbTimLoaiHang.addItem(x.getMaNhom()));
        dsnsp.forEach(x -> cbLoaiHang.addItem(x.getMaNhom()));
        dsncc.forEach(x -> cbNCC.addItem(x.getMaNCC()));
        cbTimLoaiHang.setSelectedIndex(-1);
        cbLoaiHang.setSelectedIndex(-1);
        cbNCC.setSelectedIndex(-1);
        dssp = sp_dao.getAllSanPham();
        xoaHetDuLieuTable();
        docDuLieuTuListVaoTable(dssp);
        
        Set<String> donViTinh = new HashSet<>();
        for (int i = 0; i < modelSanPham.getRowCount(); i++) {
            donViTinh.add(modelSanPham.getValueAt(i, 3).toString());
        }
        
        for (String string : donViTinh) {
            jComboBox1.addItem(string);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbTimLoaiHang = new javax.swing.JComboBox<>();
        btnTimSP = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_sp = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cbLoaiHang = new javax.swing.JComboBox<>();
        cbNCC = new javax.swing.JComboBox<>();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setMaximumSize(new java.awt.Dimension(221893422, 221893422));
        jPanel2.setPreferredSize(new java.awt.Dimension(1300, 700));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 100));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tìm Kiếm Sản Phẩm");

        txtMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSPActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tên Sản Phẩm");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Loại Hàng");

        cbTimLoaiHang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTimLoaiHangItemStateChanged(evt);
            }
        });

        btnTimSP.setBackground(new java.awt.Color(0, 102, 102));
        btnTimSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimSP.setForeground(new java.awt.Color(255, 255, 255));
        btnTimSP.setText("Tìm Kiếm");
        btnTimSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel12)))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTimSP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbTimLoaiHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(346, 346, 346)))))
                .addGap(570, 570, 570))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(btnTimSP, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbTimLoaiHang))
                .addContainerGap())
        );

        jPanel2.add(jPanel1, java.awt.BorderLayout.NORTH);

        tb_sp.setModel(modelSanPham);
        tb_sp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_spMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_sp);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 500));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        jTextField1.setEnabled(false);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã Sản Phẩm");

        jLabel2.setText("Tên Sản Phẩm");

        jLabel3.setText("Nhà Cung Cấp");

        jLabel5.setText("Giá Nhập");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Thông Tin Sản Phẩm");

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel13.setText("Ngày Nhập");

        jLabel14.setText("Ngày Sản Xuất");

        jLabel15.setText("Ngày Hết Hạn");

        jLabel8.setText("Mô Tả");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Đơn Vị Tính");

        jLabel17.setText("Số Lượng");

        jLabel18.setText("Loại Hàng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton1)
                        .addGap(38, 38, 38)
                        .addComponent(jButton2)
                        .addGap(38, 38, 38)
                        .addComponent(jButton3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50)
                                    .addComponent(cbNCC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbLoaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel9)
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLoaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tb_sp.getSelectedRow();
        if (selectedRow > -1) {
            if (JOptionPane.showConfirmDialog(this, "Xác nhận xóa sản phẩm?", "Xóa sản phẩm", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                if (sp_dao.delete(new SanPham(modelSanPham.getValueAt(selectedRow, 0).toString()))) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    xoaHetDuLieuTable();
                    dssp = sp_dao.getAllSanPham();
                    docDuLieuTuListVaoTable(dssp);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chọn sản phẩm cần xóa", "Xóa sản phẩm", JOptionPane.WARNING_MESSAGE);
            xoaHetDuLieuTable();
            dssp = sp_dao.getAllSanPham();
            docDuLieuTuListVaoTable(dssp);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int rowSelected = tb_sp.getSelectedRow();
        if (rowSelected > -1) {
            String masp=jTextField1.getText();
            String tensp=jTextField2.getText();
        
            String manhom = cbLoaiHang.getSelectedItem().toString();
            String mancc =cbNCC.getSelectedItem().toString();
            String mota =jTextField8.getText();
            double gianhap = Double.parseDouble(jTextField5.getText());
            int soluong =Integer.parseInt(jTextField9.getText());
            Date ngaynhap = jDateChooser1.getDate();
            LocalDate localDate1 = ngaynhap.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            Date ngaysx = jDateChooser2.getDate();
            LocalDate localDate2 = ngaysx.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
         
            Date ngayhh = jDateChooser3.getDate();
            LocalDate localDate3 = ngayhh.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            String dvt = (String) jComboBox1.getSelectedItem();

            SanPham sp= new SanPham(masp,tensp, mancc,mota,manhom,dvt,gianhap,localDate1,localDate2,localDate3,soluong);
            if (JOptionPane.showConfirmDialog(this, "Xác nhận sửa thông nhân viên này?", "Sửa thông tin nhân viên", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION) {
                if (sp_dao.update(sp)) {
                    JOptionPane.showMessageDialog(this, "Sửa thành công", "Sửa thông tin nhân viên", JOptionPane.INFORMATION_MESSAGE);
                    xoaHetDuLieuTable();
                    docDuLieuTuListVaoTable(sp_dao.getAllSanPham());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chọn nhân viên cần sửa thông tin",  "Sửa thông tin nhân viên", JOptionPane.INFORMATION_MESSAGE);
        }        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String masp=jTextField1.getText();
        String tensp=jTextField2.getText();
        String mancc =cbNCC.getSelectedItem().toString();
        String mota =jTextField8.getText();
        String manhom = cbLoaiHang.getSelectedItem().toString();
        double gianhap = Double.parseDouble(jTextField5.getText());
         int soluong =Integer.parseInt(jTextField9.getText());
         Date ngaynhap = jDateChooser1.getDate();
         LocalDate localDate1 = ngaynhap.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

           Date ngaysx = jDateChooser2.getDate();
         LocalDate localDate2 = ngaysx.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

           Date ngayhh = jDateChooser3.getDate();
         LocalDate localDate3 = ngayhh.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
          String dvt = (String) jComboBox1.getSelectedItem();

        SanPham sp= new SanPham(masp, tensp, mancc,mota,manhom,dvt,gianhap,localDate1,localDate2,localDate3,soluong);

        if (sp_dao.create(sp)) {
            JOptionPane.showMessageDialog(this, "Thêm thành công", "Thêm sản phẩm", JOptionPane.INFORMATION_MESSAGE);
            xoaHetDuLieuTable();
            docDuLieuTuListVaoTable(sp_dao.getAllSanPham()); 
        }
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTimSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimSPActionPerformed
        // TODO add your handling code here:
        String maSP = txtMaSP.getText();
        if (maSP == null || maSP.equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập mã sản phẩm cần tìm", "Tìm kiếm sản phẩm", JOptionPane.WARNING_MESSAGE);
        } else {
            xoaHetDuLieuTable();
            ArrayList<SanPham> dssp = new ArrayList<>();
            for (SanPham sanPham : this.dssp) {
                if (sanPham.getMaSP().toLowerCase().contains(maSP.toLowerCase())) {
                    dssp.add(sanPham);
                }
            }
            if (dssp.size()> 0) {
                for (SanPham sp : dssp) {
                    modelSanPham.addRow(new Object[] {
                        sp.getMaSP(), sp.getTenSP(), sp.getMoTa(),sp.getDonViTinh(), sp.getGiaNhap(), sp.getSoTon(), sp.getNgayNhap().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")), sp.getNgaySX().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")), sp.getNgayHH().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")), sp.getMaNhom(), sp.getMaNCC()
                    });
                }
            } else {
                JOptionPane.showMessageDialog(this, "Mã sản phẩm không tồn tại", "Tìm kiếm sản phẩm", JOptionPane.INFORMATION_MESSAGE);
                xoaHetDuLieuTable();
                docDuLieuTuListVaoTable(sp_dao.getAllSanPham());
            }
        }
    }//GEN-LAST:event_btnTimSPActionPerformed

    private void txtMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSPActionPerformed

    private void cbTimLoaiHangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTimLoaiHangItemStateChanged
         

        if (cbTimLoaiHang.getSelectedIndex() > -1) {
            String maNhomSp = cbTimLoaiHang.getSelectedItem().toString();
            dssp = sp_dao.getDSSanPhamTheoNhomSP(maNhomSp);
            if (dssp.size() > 0) {
                xoaHetDuLieuTable();
                docDuLieuTuListVaoTable(dssp);
            } else {
                JOptionPane.showMessageDialog(this, "Không có sản phẩm nào thuộc nhóm hàng này");
                xoaHetDuLieuTable();
                docDuLieuTuListVaoTable(sp_dao.getAllSanPham());
            }
        } 
    }//GEN-LAST:event_cbTimLoaiHangItemStateChanged

    private void tb_spMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_spMouseClicked
        // TODO add your handling code here:
        int rowSelected = tb_sp.getSelectedRow();
        jTextField1.setText(modelSanPham.getValueAt(rowSelected, 0).toString());
        jTextField1.setEditable(false);
        jTextField1.setEnabled(false);
        jTextField2.setText(modelSanPham.getValueAt(rowSelected, 1).toString());
        cbNCC.setSelectedItem(modelSanPham.getValueAt(rowSelected, 10).toString());
        jTextField8.setText(modelSanPham.getValueAt(rowSelected, 2).toString());
        jTextField5.setText(modelSanPham.getValueAt(rowSelected, 4).toString());
        jTextField9.setText(modelSanPham.getValueAt(rowSelected, 5).toString());
        jComboBox1.setSelectedItem(modelSanPham.getValueAt(rowSelected, 3).toString());
        cbLoaiHang.setSelectedItem(modelSanPham.getValueAt(rowSelected, 9).toString());
        try {
            jDateChooser1.setDate(new SimpleDateFormat("dd-MM-yyyy").parse(modelSanPham.getValueAt(rowSelected, 6).toString()));
            jDateChooser2.setDate(new SimpleDateFormat("dd-MM-yyyy").parse(modelSanPham.getValueAt(rowSelected, 7).toString()));
            jDateChooser3.setDate(new SimpleDateFormat("dd-MM-yyyy").parse(modelSanPham.getValueAt(rowSelected, 8).toString()));
        } catch (ParseException ex) {
            Logger.getLogger(Panel_QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tb_spMouseClicked

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    public void xoaHetDuLieuTable() {
        DefaultTableModel dtm = (DefaultTableModel)tb_sp.getModel();
        dtm.getDataVector().removeAllElements();
    }
    
    public void docDuLieuTuListVaoTable(ArrayList<SanPham> dssp) {
        for (SanPham sp : dssp) {
            modelSanPham.addRow(new Object[] {
                sp.getMaSP(), sp.getTenSP(), sp.getMoTa(),sp.getDonViTinh(), String.format("%.0f", sp.getGiaNhap()), sp.getSoTon(), sp.getNgayNhap().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")), sp.getNgaySX().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")), sp.getNgayHH().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")), sp.getMaNhom(), sp.getMaNCC()
            });
        }
        tb_sp.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimSP;
    private javax.swing.JComboBox<String> cbLoaiHang;
    private javax.swing.JComboBox<String> cbNCC;
    private javax.swing.JComboBox<String> cbTimLoaiHang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTable tb_sp;
    private javax.swing.JTextField txtMaSP;
    // End of variables declaration//GEN-END:variables
}
